export const QUERY_KEYS = {
  leads: {
    all: ['leads'],
    list: (filters) => ['leads', 'list', filters],
    detail: (id) => ['leads', 'detail', id],
    myLeads: ['leads', 'my-leads'],
  },
  customers: {
    all: ['customers'],
    list: (filters) => ['customers', 'list', filters],
    detail: (id) => ['customers', 'detail', id],
    deleted: ['customers', 'deleted'],
  },
  teams: {
    all: ['teams'],
    list: ['teams', 'list'],
    detail: (id) => ['teams', 'detail', id],
  },
  tasks: {
    all: ['tasks'],
    list: (filters) => ['tasks', 'list', filters],
    detail: (id) => ['tasks', 'detail', id],
  },
  proposalTemplates: {
    all: ['proposal-templates'],
    list: (filters) => ['proposal-templates', 'list', filters],
    detail: (id) => ['proposal-templates', 'detail', id],
    versions: (templateId, filters) => ['proposal-templates', templateId, 'versions', filters],
    version: (versionId) => ['proposal-templates', 'versions', versionId],
    sections: (versionId, filters) => ['proposal-templates', 'versions', versionId, 'sections', filters],
    section: (sectionId) => ['proposal-templates', 'sections', sectionId],
    blocks: (sectionId, filters) => ['proposal-templates', 'sections', sectionId, 'blocks', filters],
    block: (blockId) => ['proposal-templates', 'blocks', blockId],
  },
  proposals: {
    all: ['proposals'],
    list: (filters) => ['proposals', 'list', filters],
    detail: (proposalId) => ['proposals', 'detail', proposalId],
    versions: (proposalId, filters) => ['proposals', proposalId, 'versions', filters],
    version: (proposalId, versionId) => ['proposals', proposalId, 'version', versionId],
    options: (proposalId, filters) => ['proposals', proposalId, 'options', filters],
    optionItems: (proposalId, optionId, filters) => ['proposals', proposalId, 'options', optionId, 'items', filters],
  },
  meetings: {
    all: ['meetings'],
    list: (filters) => ['meetings', 'list', filters],
    detail: (id) => ['meetings', 'detail', id],
    leadCallsMeetings: (leadId, filters) => ['meetings', 'lead', leadId, 'calls-meetings', filters],
    reports: (id, filters) => ['meetings', id, 'reports', filters],
    reportsSummary: (filters) => ['meetings', 'reports', 'summary', filters],
  },
  users: {
    all: ['users'],
    list: ['users', 'list'],
  },
  statuses: {
    all: ['statuses'],
    list: ['statuses', 'list'],
  },
  tags: {
    all: ['tags'],
    list: ['tags', 'list'],
  },
  conversations: {
    all: ['conversations'],
    list: (tenant) => ['conversations', 'list', tenant],
    messages: (tenant, id) => ['conversations', 'messages', tenant, id],
  },
  campaigns: {
    all: ['campaigns'],
    active: ['campaigns', 'active'],
    inactive: ['campaigns', 'inactive'],
    detail: (id) => ['campaigns', 'detail', id],
  },
  messegeCampaigns: {
    all: ['messege-campaigns'],
    list: (filters) => ['messege-campaigns', 'list', filters],
    detail: (id) => ['messege-campaigns', 'detail', id],
    scheduled: (filters) => ['messege-campaigns', 'scheduled', filters],
    my: (filters) => ['messege-campaigns', 'my', filters],
    myScheduled: (filters) => ['messege-campaigns', 'my', 'scheduled', filters],
  },
  whatsappTemplateImages: {
    all: ['whatsapp-template-images'],
    list: (filters) => ['whatsapp-template-images', 'list', filters],
    byTemplate: (templateId) => ['whatsapp-template-images', 'template', templateId],
  },
  metaIntegrations: {
    all: ['meta-integrations'],
    facebookPages: (tenant, filters) => ['meta-integrations', 'facebook', 'pages', tenant, filters],
    facebookAssets: (tenant, filters) => ['meta-integrations', 'facebook', 'assets', tenant, filters],
    whatsappChats: (tenant, filters) => ['meta-integrations', 'whatsapp', 'chats', tenant, filters],
    whatsappMessages: (tenant, conversationId, filters) => [
      'meta-integrations',
      'whatsapp',
      'messages',
      tenant,
      conversationId,
      filters,
    ],
    whatsappTemplates: (tenant, filters) => ['meta-integrations', 'whatsapp', 'templates', tenant, filters],
    messengerConversations: (filters) => ['meta-integrations', 'messenger', 'conversations', filters],
    messengerConversation: (conversationId, filters) => [
      'meta-integrations',
      'messenger',
      'conversation',
      conversationId,
      filters,
    ],
    messengerMessages: (conversationId, filters) => [
      'meta-integrations',
      'messenger',
      'messages',
      conversationId,
      filters,
    ],
  },
  assignmentRules: {
    all: ['assignment-rules'],
    list: ['assignment-rules', 'list'],
  },
  dashboard: {
    myLeads: ['dashboard', 'my-leads'],
    myTeams: ['dashboard', 'my-teams'],
  },
}
