// Components of the deals feature, composed by the route pages in pages/deals.
export { DealsHubLayout } from './layout/DealsHubLayout'
export { DealWorkspaceLayout } from './layout/DealWorkspaceLayout'
export { DealWorkspaceHeader } from './layout/DealWorkspaceHeader'
export { DealOverview } from './overview/DealOverview'
export { DealPipelineView } from './pipeline/DealPipelineView'
export { DealTeamPanel } from './team/DealTeamPanel'
export { DealProductsPanel } from './products/DealProductsPanel'
export { DealContractsTable } from './contracts/DealContractsTable'
export { ContractDrawer } from './contracts/ContractDrawer'
export { DealActivitiesPanel } from './activities/DealActivitiesPanel'
export { DealTasksPanel } from './tasks/DealTasksPanel'
export { DealCalendar } from './calendar/DealCalendar'
export { DealAssistant } from './ai/DealAssistant'
export { DealGeneralSettings } from './settings/DealGeneralSettings'
export { DealStagesSettings } from './settings/DealStagesSettings'
export { DealPreferencesSettings } from './settings/DealPreferencesSettings'
export { DealDangerZone } from './settings/DealDangerZone'
export { DealsTable } from './hub/DealsTable'
export { CreateDealDialog } from './hub/CreateDealDialog'
export { PipelineTemplatesPanel } from './hub/PipelineTemplatesPanel'
export { WonDialog } from './closing/WonDialog'
export { LostDialog } from './closing/LostDialog'
export { DealStatusBadge, LeadStatusBadge } from './common/DealStatusBadge'
export { PlannedNotice } from './common/PlannedNotice'
