export default {
  "closing": {
    "lines": {
      "product": "Product",
      "quantity": "Qty",
      "unitPrice": "Unit price",
      "discount": "Discount",
      "total": "Total",
      "remove": "Remove line",
      "add": "Add product",
      "grandTotal": "Total"
    },
    "won": {
      "title": "Mark as won",
      "description": "Close {{name}} as won. The contract, payment plan and follow-up tasks are created by the system.",
      "products": "Products",
      "paymentType": "Payment type",
      "downPayment": "Down payment",
      "cashHint": "For cash, usually the full amount.",
      "installments": "Number of installments",
      "frequency": "Every",
      "interestRate": "Interest rate %",
      "noInterestHint": "No interest for this payment type.",
      "firstDueDate": "First due date",
      "previewTitle": "Schedule preview",
      "previewNote": "Estimate only. The final schedule is generated by the system when you confirm.",
      "installmentN": "Installment {{number}}",
      "stagesNotes": "Stages and amounts",
      "customStagedHint": "The payment stages are set on the contract after closing.",
      "serverTotalNote": "Preview total: {{total}}. The final total is calculated by the system from the saved products.",
      "submit": "Confirm won",
      "success": "Lead won.",
      "successWithContract": "Lead won. Contract {{number}} created.",
      "failed": "Could not close the lead as won. Nothing was created.",
      "errors": {
        "itemsRequired": "Add at least one product with a quantity.",
        "paymentTypeRequired": "Choose a payment type.",
        "downPaymentNegative": "The down payment cannot be negative.",
        "downPaymentTooHigh": "The down payment is higher than the total.",
        "installmentsRequired": "Enter the number of installments.",
        "frequencyRequired": "Choose how often installments are due.",
        "firstDueDateRequired": "Choose the first due date."
      }
    },
    "lost": {
      "title": "Mark as lost",
      "description": "Close {{name}} as lost.",
      "reason": "Reason",
      "submit": "Confirm lost",
      "success": "Lead marked as lost.",
      "failed": "Could not close the lead as lost."
    }
  }
}
