import { isMetaCampaignObjective } from '../config/metaObjectives'
import { getAdSetOptionsForObjective, getAdSetRequirements, isVideoGoal } from '../config/metaAdSetCompatibility'
import { AD_TEXT_LIMITS, CAROUSEL_LIMITS, getCallToActions } from '../config/metaCallToActions'
import { getUnsupportedPlatforms, PLACEMENT_PLATFORMS } from '../config/metaPlacements'
import { hasRestrictedTargeting, requiresPoliticalAuthorization, RESTRICTED_TARGETING } from '../config/metaSpecialAdCategories'
import { WIZARD_PUBLISH_CAPABILITIES } from '../config/wizardCapabilities'
import { getSuggestedDailyMinimum, isPositiveNumber } from '../utils/campaignMoney'
import { analyzeGeoSelection } from './geoTargeting'
import { diffHours, isInPast } from './accountTime'
import { isValidHttpUrl, isValidInternationalPhone } from './contactFormats'

/**
 * Validates the whole wizard in one pass.
 *
 * Every issue has:
 *   code      → i18n key `campaignWizard.issues.<code>`
 *   severity  → 'error' blocks publishing, 'warning' is shown but allowed, 'info' is advice
 *   stage     → which wizard stage owns it (stepper badges, guide checklist)
 *   path      → the field it belongs to (inline errors, "jump to field")
 */
export function validateWizard(state, context = {}) {
  const capabilities = { ...WIZARD_PUBLISH_CAPABILITIES, ...context.capabilities }
  const tz = context.timezone
  const currency = context.currency
  const issues = []
  const add = (issue) => issues.push({ severity: 'error', params: {}, ...issue, id: `${issue.stage}:${issue.path}:${issue.code}` })

  // Objective ---------------------------------------------------------------
  if (!isMetaCampaignObjective(state.objective)) add({ stage: 'objective', path: 'objective', code: 'objectiveRequired' })

  // Campaign ----------------------------------------------------------------
  const campaign = state.campaign
  if (campaign.name && campaign.name.length > 250) add({ stage: 'campaignSetup', path: 'campaign.name', code: 'nameTooLong', params: { max: 250 } })
  if (!campaign.name?.trim()) add({ stage: 'campaignSetup', path: 'campaign.name', code: 'nameAutoGenerated', severity: 'info' })
  if (!campaign.pageId) add({ stage: 'campaignSetup', path: 'campaign.pageId', code: 'pageRequired' })
  else if (context.pages && !context.pages.some((page) => String(page.page_id || page.id) === String(campaign.pageId))) add({ stage: 'campaignSetup', path: 'campaign.pageId', code: 'pageUnavailable' })
  if (campaign.specialAdCategories.length && !campaign.specialAdCategoryCountries?.length) add({ stage: 'campaignSetup', path: 'campaign.specialAdCategoryCountries', code: 'specialCountriesRequired' })
  if (requiresPoliticalAuthorization(campaign.specialAdCategories)) add({ stage: 'campaignSetup', path: 'campaign.specialAdCategories', code: 'politicalAuthorization', severity: 'warning' })

  if (campaign.budgetLevel === 'campaign') validateBudgetOwner(add, campaign, { stage: 'campaignSetup', prefix: 'campaign', currency })
  validateSchedule(add, campaign.schedule, { stage: 'campaignSetup', prefix: 'campaign.schedule', tz, lifetime: campaign.budgetLevel === 'campaign' && campaign.budgetType === 'lifetime' })
  if (campaign.budgetLevel === 'campaign' && isPositiveNumber(campaign.spendCap) && isPositiveNumber(campaign.budgetAmount) && Number(campaign.spendCap) < Number(campaign.budgetAmount)) {
    add({ stage: 'campaignSetup', path: 'campaign.spendCap', code: 'spendCapBelowBudget', severity: 'warning' })
  }

  // Ad sets -----------------------------------------------------------------
  if (!state.adSets.length) add({ stage: 'adSets', path: 'adSets', code: 'adSetRequired' })
  const restricted = hasRestrictedTargeting(campaign.specialAdCategories)
  for (const adSet of state.adSets) validateAdSet(add, state, adSet, { tz, currency, restricted })

  // Ads ---------------------------------------------------------------------
  const adSeverity = capabilities.createAds ? 'error' : 'warning'
  if (!capabilities.createAds) add({ stage: 'ads', path: 'ads', code: 'adsApiPending', severity: 'info' })
  for (const adSet of state.adSets) {
    if (!adSet.ads?.length) add({ stage: 'ads', path: `adSets.${adSet.id}.ads`, code: 'adRequired', severity: adSeverity, adSetId: adSet.id })
    for (const ad of adSet.ads || []) validateAd(add, state, adSet, ad, { severity: adSeverity })
  }

  // Review ------------------------------------------------------------------
  if (['OUTCOME_LEADS'].includes(state.objective) || state.adSets.some((adSet) => ['instant_form', 'whatsapp', 'messenger', 'messaging_apps', 'instagram_direct'].includes(adSet.conversionLocation))) {
    if (!state.leadRouting?.teamId) add({ stage: 'review', path: 'leadRouting.teamId', code: 'leadRoutingRecommended', severity: 'info' })
  }

  return issues
}

function validateBudgetOwner(add, owner, { stage, prefix, currency, adSetId }) {
  if (!isPositiveNumber(owner.budgetAmount)) {
    add({ stage, path: `${prefix}.budgetAmount`, code: 'budgetRequired', adSetId })
  } else if (owner.budgetType === 'daily') {
    const minimum = getSuggestedDailyMinimum(currency)
    if (minimum && Number(owner.budgetAmount) < minimum) add({ stage, path: `${prefix}.budgetAmount`, code: 'budgetBelowSuggested', severity: 'warning', params: { minimum, currency }, adSetId })
  }
  if (['cost_cap', 'bid_cap'].includes(owner.bidStrategy) && !isPositiveNumber(owner.bidAmount)) add({ stage, path: `${prefix}.bidAmount`, code: 'bidAmountRequired', adSetId })
  if (owner.bidStrategy === 'minimum_roas' && !isPositiveNumber(owner.roasFloor)) add({ stage, path: `${prefix}.roasFloor`, code: 'roasRequired', adSetId })
}

function validateSchedule(add, schedule, { stage, prefix, tz, lifetime, adSetId }) {
  if (!schedule) return
  if (schedule.startType === 'scheduled') {
    if (!schedule.startTime) add({ stage, path: `${prefix}.startTime`, code: 'startTimeRequired', adSetId })
    else if (isInPast(schedule.startTime, tz, 5)) add({ stage, path: `${prefix}.startTime`, code: 'startInPast', adSetId })
  }
  if (schedule.endType === 'scheduled' || lifetime) {
    if (!schedule.endTime) add({ stage, path: `${prefix}.endTime`, code: lifetime ? 'lifetimeEndRequired' : 'endTimeRequired', adSetId })
    else if (isInPast(schedule.endTime, tz)) add({ stage, path: `${prefix}.endTime`, code: 'endInPast', adSetId })
    else {
      const start = schedule.startType === 'scheduled' && schedule.startTime ? schedule.startTime : null
      const hours = start ? diffHours(start, schedule.endTime, tz) : null
      if (hours !== null && hours <= 0) add({ stage, path: `${prefix}.endTime`, code: 'endBeforeStart', adSetId })
      else if (lifetime && hours !== null && hours < 24) add({ stage, path: `${prefix}.endTime`, code: 'lifetimeTooShort', severity: 'warning', adSetId })
    }
  }
}

function validateAdSet(add, state, adSet, { tz, currency, restricted }) {
  const stage = 'adSets'
  const base = `adSets.${adSet.id}`
  const adSetId = adSet.id
  const options = getAdSetOptionsForObjective(state.objective, adSet.conversionLocation)
  const requirements = getAdSetRequirements(state.objective, adSet)

  if (state.objective && !options.locations.includes(adSet.conversionLocation)) add({ stage, path: `${base}.conversionLocation`, code: 'conversionLocationRequired', adSetId })
  else if (adSet.performanceGoal && !options.goals.includes(adSet.performanceGoal)) add({ stage, path: `${base}.performanceGoal`, code: 'goalIncompatible', adSetId })

  if (requirements.has('whatsapp')) {
    if (!adSet.whatsappPhoneNumber) add({ stage, path: `${base}.whatsappPhoneNumber`, code: 'whatsappRequired', adSetId })
    else if (!isValidInternationalPhone(adSet.whatsappPhoneNumber)) add({ stage, path: `${base}.whatsappPhoneNumber`, code: 'phoneInvalid', adSetId })
  }
  if (requirements.has('instagram') && !adSet.instagramAccountId) add({ stage, path: `${base}.instagramAccountId`, code: 'instagramRequired', adSetId })
  if (requirements.has('pixel')) {
    if (!adSet.pixelId) add({ stage, path: `${base}.pixelId`, code: 'pixelRequired', adSetId })
    if (!adSet.customEventType) add({ stage, path: `${base}.customEventType`, code: 'eventRequired', adSetId })
  }
  if (requirements.has('app')) {
    if (!adSet.applicationId) add({ stage, path: `${base}.applicationId`, code: 'appRequired', adSetId })
    if (!isValidHttpUrl(adSet.objectStoreUrl)) add({ stage, path: `${base}.objectStoreUrl`, code: 'storeUrlInvalid', adSetId })
  }
  if (requirements.has('appEvent') && !adSet.customEventType) add({ stage, path: `${base}.customEventType`, code: 'eventRequired', adSetId })
  if (requirements.has('event') && !adSet.eventId) add({ stage, path: `${base}.eventId`, code: 'eventIdRequired', adSetId })
  if (requirements.has('frequencyCap') && (!isPositiveNumber(adSet.frequencyMax) || !isPositiveNumber(adSet.frequencyIntervalDays))) add({ stage, path: `${base}.frequencyMax`, code: 'frequencyRequired', adSetId })

  // Audience
  const audience = adSet.audience
  const geoProblems = analyzeGeoSelection(audience.geo, { minRadiusKm: restricted ? RESTRICTED_TARGETING.minRadiusKm : 0 })
  for (const problem of geoProblems) {
    const code = { noIncludedLocation: 'geoNoLocation', includedAndExcluded: 'geoIncludedAndExcluded', exclusionOutsideInclusion: 'geoExclusionOutside', redundantLocation: 'geoRedundant', radiusOutOfRange: 'geoRadiusOutOfRange' }[problem.code]
    const severity = ['exclusionOutsideInclusion', 'redundantLocation'].includes(problem.code) ? 'warning' : 'error'
    add({ stage, path: `${base}.audience.geo${problem.key ? `.${problem.key}` : ''}`, code, severity, params: { min: problem.min, max: problem.max }, adSetId })
  }
  const ageMin = Number(audience.ageMin)
  const ageMax = Number(audience.ageMax)
  if (!Number.isInteger(ageMin) || !Number.isInteger(ageMax) || ageMin < 13 || ageMax > 65 || ageMin > ageMax) add({ stage, path: `${base}.audience.age`, code: 'ageInvalid', adSetId })
  else if (ageMin < 18) add({ stage, path: `${base}.audience.age`, code: 'ageUnder18', severity: 'warning', adSetId })
  if (restricted) {
    if (audience.detailedExclusions?.length) add({ stage, path: `${base}.audience.detailedExclusions`, code: 'specialNoExclusions', adSetId })
    if ((audience.customAudienceIds || []).some((id) => /lal|lookalike/i.test(id))) add({ stage, path: `${base}.audience.customAudienceIds`, code: 'specialNoLookalike', adSetId })
  }
  if (restricted && audience.geo?.locations?.some((item) => item.type === 'zip')) add({ stage, path: `${base}.audience.geo`, code: 'specialNoZip', adSetId })

  // Placements
  if (adSet.placements?.mode === 'manual') {
    const selected = Object.entries(adSet.placements.manual || {}).filter(([, positions]) => positions?.length)
    if (!selected.length) add({ stage, path: `${base}.placements`, code: 'placementsRequired', adSetId })
    const unsupported = getUnsupportedPlatforms(adSet.conversionLocation)
    if (selected.some(([platform]) => unsupported.includes(platform) || !PLACEMENT_PLATFORMS[platform])) add({ stage, path: `${base}.placements`, code: 'placementsUnsupported', adSetId })
    if (!adSet.placements.devices?.length) add({ stage, path: `${base}.placements.devices`, code: 'devicesRequired', adSetId })
  }

  // Budget & schedule
  if (state.campaign.budgetLevel === 'adSet') validateBudgetOwner(add, adSet, { stage, prefix: base, currency, adSetId })
  const ownsSchedule = state.campaign.budgetLevel === 'adSet' && !adSet.useCampaignSchedule
  if (ownsSchedule) validateSchedule(add, adSet.schedule, { stage, prefix: `${base}.schedule`, tz, lifetime: adSet.budgetType === 'lifetime', adSetId })
  else if (state.campaign.budgetLevel === 'adSet' && adSet.budgetType === 'lifetime' && state.campaign.schedule.endType !== 'scheduled') {
    add({ stage, path: `${base}.schedule.endTime`, code: 'lifetimeEndRequired', adSetId })
  }
  const lifetimeOwner = state.campaign.budgetLevel === 'campaign' ? state.campaign.budgetType === 'lifetime' : adSet.budgetType === 'lifetime'
  if (adSet.dayparting?.enabled) {
    if (!lifetimeOwner) add({ stage, path: `${base}.dayparting`, code: 'daypartingNeedsLifetime', adSetId })
    if (!adSet.dayparting.days?.length) add({ stage, path: `${base}.dayparting`, code: 'daypartingNoDays', adSetId })
    if (Number(adSet.dayparting.startHour) >= Number(adSet.dayparting.endHour)) add({ stage, path: `${base}.dayparting`, code: 'daypartingHours', adSetId })
  }
}

function validateAd(add, state, adSet, ad, { severity }) {
  const stage = 'ads'
  const base = `ads.${ad.id}`
  const ids = { adSetId: adSet.id, adId: ad.id }
  const requirements = getAdSetRequirements(state.objective, adSet)
  const push = (path, code, overrides = {}) => add({ stage, path: `${base}.${path}`, code, severity, ...ids, ...overrides })

  if (ad.format === 'existing_post') {
    if (!ad.existingPostId) push('existingPostId', 'existingPostRequired')
  } else if (ad.format === 'carousel') {
    const cards = ad.carouselCards || []
    if (cards.length < CAROUSEL_LIMITS.min) push('carouselCards', 'carouselMinCards', { params: { min: CAROUSEL_LIMITS.min } })
    if (cards.some((card) => !card.media)) push('carouselCards', 'carouselCardMedia')
    if (requirements.has('websiteUrl') && cards.some((card) => card.link && !isValidHttpUrl(card.link))) push('carouselCards', 'websiteUrlInvalid')
  } else if (!ad.media) {
    push('media', 'mediaRequired')
  } else if (ad.format === 'single_video' && ad.media.type !== 'video') {
    push('media', 'videoRequired')
  }
  if (isVideoGoal(adSet.performanceGoal) && ad.format !== 'single_video' && ad.format !== 'existing_post') push('format', 'videoGoalNeedsVideo')

  if (ad.format !== 'existing_post') {
    const primaryTexts = (ad.primaryTexts || []).filter((text) => text?.trim())
    if (!primaryTexts.length) push('primaryTexts', 'primaryTextRequired')
    if (primaryTexts.some((text) => text.length > AD_TEXT_LIMITS.primaryText)) push('primaryTexts', 'primaryTextLong', { severity: 'info', params: { max: AD_TEXT_LIMITS.primaryText } })
    if ((ad.headlines || []).some((text) => text?.length > AD_TEXT_LIMITS.headline)) push('headlines', 'headlineLong', { severity: 'info', params: { max: AD_TEXT_LIMITS.headline } })
    if (!(ad.headlines || []).some((text) => text?.trim()) && ad.format !== 'carousel') push('headlines', 'headlineRecommended', { severity: 'info' })
  }
  if (!getCallToActions(adSet.conversionLocation).includes(ad.callToAction)) push('callToAction', 'ctaInvalid')

  if (requirements.has('websiteUrl') && ad.format !== 'existing_post') {
    if (!ad.websiteUrl?.trim()) push('websiteUrl', 'websiteUrlRequired')
    else if (!isValidHttpUrl(ad.websiteUrl)) push('websiteUrl', 'websiteUrlInvalid')
  }
  if (requirements.has('leadForm')) validateLeadForm(push, ad.leadForm)
  if (requirements.has('phone')) {
    if (!ad.phoneNumber) push('phoneNumber', 'phoneRequired')
    else if (!isValidInternationalPhone(ad.phoneNumber)) push('phoneNumber', 'phoneInvalid')
  }
  if (requirements.has('messageTemplate') && !ad.messageTemplate?.greeting?.trim()) push('messageTemplate', 'greetingRecommended', { severity: 'info' })
}

function validateLeadForm(push, leadForm) {
  if (leadForm?.mode !== 'new') {
    if (!leadForm?.formId) push('leadForm', 'leadFormRequired')
    return
  }
  const draft = leadForm.draft || {}
  if (!draft.name?.trim()) push('leadForm.name', 'leadFormNameRequired')
  if (!draft.questions?.length && !draft.customQuestions?.length) push('leadForm.questions', 'leadFormQuestionsRequired')
  if (!draft.questions?.some((question) => question.type === 'PHONE')) push('leadForm.questions', 'leadFormPhoneRecommended', { severity: 'warning' })
  if (draft.customQuestions?.some((question) => !question.label?.trim() || (question.kind === 'choice' && (question.options || []).filter((option) => option.trim()).length < 2))) push('leadForm.customQuestions', 'leadFormCustomQuestionIncomplete')
  if (!isValidHttpUrl(draft.privacyPolicyUrl)) push('leadForm.privacyPolicyUrl', 'leadFormPrivacyRequired')
  if (draft.thankYou?.buttonType === 'VIEW_WEBSITE' && draft.thankYou.website && !isValidHttpUrl(draft.thankYou.website)) push('leadForm.thankYou.website', 'websiteUrlInvalid')
  if (draft.thankYou?.buttonType === 'CALL_BUSINESS' && !isValidInternationalPhone(draft.thankYou.phone)) push('leadForm.thankYou.phone', 'phoneInvalid')
}

// Helpers used by the UI --------------------------------------------------

export function issuesForStage(issues, stage) {
  return issues.filter((issue) => issue.stage === stage)
}

export function blockingIssues(issues) {
  return issues.filter((issue) => issue.severity === 'error')
}

export function issuesForPath(issues, path) {
  return issues.filter((issue) => issue.path === path || issue.path.startsWith(`${path}.`))
}

/** 'complete' | 'error' | 'warning' — used by the stepper and drafts list. */
export function stageStatus(issues, stage) {
  const stageIssues = issuesForStage(issues, stage)
  if (stageIssues.some((issue) => issue.severity === 'error')) return 'error'
  if (stageIssues.some((issue) => issue.severity === 'warning')) return 'warning'
  return 'complete'
}

/** Rough completion percentage for the drafts sidebar and header. */
export function completionPercent(issues, stages) {
  const complete = stages.filter((stage) => stageStatus(issues, stage) !== 'error').length
  return Math.round((complete / stages.length) * 100)
}
